In [0]:
from google.colab import drive
drive.mount('/content/gdrive/')

In [0]:
import os
os.listdir('/content/gdrive/')

['Team Drives', 'My Drive', '.Trash']

In [0]:
data_dir = os.path.join('/content/gdrive', 'My Drive', 'workspace', 'colab_notebooks', 'intro_colab')

Now, lets look at the data. This is data from World Health Organization and you can download it [here](https://drive.google.com/open?id=1HXNRVK9nnxBFcXdRxcprOzJoDtAqdRK0)


In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import PIL
import numpy as np 
import seaborn as sns

In [0]:
!pip install -q keras
import keras

Using TensorFlow backend.


In [0]:
keras

In [0]:
os.listdir(data_dir)

['master.csv', 'Rad_Panda.ipynb']

In [0]:
m_data = pd.read_csv(os.path.join(data_dir, 'master.csv'))

In [0]:
m_data.head()

country  year     sex          age  suicides_no  population  \
0  Albania  1987    male  15-24 years           21      312900   
1  Albania  1987    male  35-54 years           16      308000   
2  Albania  1987  female  15-24 years           14      289700   
3  Albania  1987    male    75+ years            1       21800   
4  Albania  1987    male  25-34 years            9      274300   

   suicides/100k pop country-year  HDI for year  gdp_for_year ($)   \
0               6.71  Albania1987           NaN      2,156,624,900   
1               5.19  Albania1987           NaN      2,156,624,900   
2               4.83  Albania1987           NaN      2,156,624,900   
3               4.59  Albania1987           NaN      2,156,624,900   
4               3.28  Albania1987           NaN      2,156,624,900   

   gdp_per_capita ($)       generation  
0                 796     Generation X  
1                 796           Silent  
2                 796     Generation X  
3                 796  G.I. Generation  
4                 796          Boomers

In [0]:
#show data at the bottom
m_data.tail()

country  year     sex          age  suicides_no  population  \
27815  Uzbekistan  2014  female  35-54 years          107     3620833   
27816  Uzbekistan  2014  female    75+ years            9      348465   
27817  Uzbekistan  2014    male   5-14 years           60     2762158   
27818  Uzbekistan  2014  female   5-14 years           44     2631600   
27819  Uzbekistan  2014  female  55-74 years           21     1438935   

       suicides/100k pop    country-year  HDI for year  gdp_for_year ($)   \
27815               2.96  Uzbekistan2014         0.675     63,067,077,179   
27816               2.58  Uzbekistan2014         0.675     63,067,077,179   
27817               2.17  Uzbekistan2014         0.675     63,067,077,179   
27818               1.67  Uzbekistan2014         0.675     63,067,077,179   
27819               1.46  Uzbekistan2014         0.675     63,067,077,179   

       gdp_per_capita ($)    generation  
27815                2309  Generation X  
27816                2309        Silent  
27817                2309  Generation Z  
27818                2309  Generation Z  
27819                2309       Boomers

In [0]:
#random sample of data, shows that some columns have HDI 
m_data.sample(15)

country  year     sex          age  suicides_no  \
9969                        Germany  2011  female  35-54 years          757   
23061                      Slovenia  1997    male  55-74 years          138   
4581                       Bulgaria  1988  female    75+ years          102   
7607                        Denmark  2009  female  15-24 years            4   
7919                        Ecuador  2003  female   5-14 years           20   
17595                   New Zealand  1997    male  35-54 years          120   
6439                        Croatia  2000  female   5-14 years            0   
812                       Argentina  2003  female  35-54 years          196   
27778                    Uzbekistan  2011    male    75+ years           10   
7969                        Ecuador  2007  female    75+ years            2   
8644                           Fiji  2004    male  25-34 years            4   
21713  Saint Vincent and Grenadines  1997    male   5-14 years            0   
15181                     Lithuania  2006  female    75+ years           37   
21262         Saint Kitts and Nevis  1990  female  35-54 years            0   
15141                     Lithuania  2003    male  55-74 years          288   

       population  suicides/100k pop                      country-year  \
9969     12196847               6.21                       Germany2011   
23061      170200              81.08                      Slovenia1997   
4581       241000              42.32                      Bulgaria1988   
7607       324876               1.23                       Denmark2009   
7919      1442546               1.39                       Ecuador2003   
17595      508800              23.58                   New Zealand1997   
6439       295200               0.00                       Croatia2000   
812       4402438               4.45                     Argentina2003   
27778      204956               4.88                    Uzbekistan2011   
7969       180159               1.11                       Ecuador2007   
8644        63091               6.34                          Fiji2004   
21713       12124               0.00  Saint Vincent and Grenadines1997   
15181      159540              23.19                     Lithuania2006   
21262        2900               0.00         Saint Kitts and Nevis1990   
15141      274066             105.08                     Lithuania2003   

       HDI for year  gdp_for_year ($)   gdp_per_capita ($)       generation  
9969          0.911  3,757,698,281,118               47947     Generation X  
23061           NaN     20,749,140,606               11014           Silent  
4581            NaN     22,555,941,176                2688  G.I. Generation  
7607            NaN    321,241,396,034               61863       Millenials  
7919            NaN     32,432,858,000                2755       Millenials  
17595           NaN     66,074,513,018               19041          Boomers  
6439          0.749     21,774,273,832                5288       Millenials  
812             NaN    127,586,973,492                3668          Boomers  
27778         0.661     45,915,191,189                1767           Silent  
7969            NaN     51,007,777,000                4024           Silent  
8644            NaN      2,727,507,213                3744     Generation X  
21713           NaN        347,770,000                3613       Millenials  
15181           NaN     30,216,060,233                9667           Silent  
21262           NaN        208,740,444                5339           Silent  
15141           NaN     18,802,576,988                5778           Silent

In [0]:
#The describe function in pandas is where you should start
m_data.describe()

year   suicides_no    population  suicides/100k pop  \
count  27820.000000  27820.000000  2.782000e+04       27820.000000   
mean    2001.258375    242.574407  1.844794e+06          12.816097   
std        8.469055    902.047917  3.911779e+06          18.961511   
min     1985.000000      0.000000  2.780000e+02           0.000000   
25%     1995.000000      3.000000  9.749850e+04           0.920000   
50%     2002.000000     25.000000  4.301500e+05           5.990000   
75%     2008.000000    131.000000  1.486143e+06          16.620000   
max     2016.000000  22338.000000  4.380521e+07         224.970000   

       HDI for year  gdp_per_capita ($)  
count   8364.000000        27820.000000  
mean       0.776601        16866.464414  
std        0.093367        18887.576472  
min        0.483000          251.000000  
25%        0.713000         3447.000000  
50%        0.779000         9372.000000  
75%        0.855000        24874.000000  
max        0.944000       126352.000000

In [0]:
m_data.iloc[:,1:5].describe()

year   suicides_no
count  27820.000000  27820.000000
mean    2001.258375    242.574407
std        8.469055    902.047917
min     1985.000000      0.000000
25%     1995.000000      3.000000
50%     2002.000000     25.000000
75%     2008.000000    131.000000
max     2016.000000  22338.000000

In [0]:
m_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 12 columns):
country               27820 non-null object
year                  27820 non-null int64
sex                   27820 non-null object
age                   27820 non-null object
suicides_no           27820 non-null int64
population            27820 non-null int64
suicides/100k pop     27820 non-null float64
country-year          27820 non-null object
HDI for year          8364 non-null float64
 gdp_for_year ($)     27820 non-null object
gdp_per_capita ($)    27820 non-null int64
generation            27820 non-null object
dtypes: float64(2), int64(4), object(6)
memory usage: 2.5+ MB


In [0]:
m_data.columns

Index(['country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation'],
      dtype='object')

In [0]:
m_data = m_data.rename(columns={'country':'Country','year':'Year','sex':'Gender','age':'Age','suicides_no':'SuicidesNo','population':'Population','suicides/100k pop':'Suicides100kPop','country-year':'CountryYear','HDI for year':'HDIForYear',' gdp_for_year ($) ':'GdpForYearMoney','gdp_per_capita ($)':'GdpPerCapitalMoney','generation':'Generation'})

In [0]:
m_data.head()

Country  Year  Gender          Age  SuicidesNo  Population  \
0  Albania  1987    male  15-24 years          21      312900   
1  Albania  1987    male  35-54 years          16      308000   
2  Albania  1987  female  15-24 years          14      289700   
3  Albania  1987    male    75+ years           1       21800   
4  Albania  1987    male  25-34 years           9      274300   

   Suicides100kPop  CountryYear  HDIForYear GdpForYearMoney  \
0             6.71  Albania1987         NaN   2,156,624,900   
1             5.19  Albania1987         NaN   2,156,624,900   
2             4.83  Albania1987         NaN   2,156,624,900   
3             4.59  Albania1987         NaN   2,156,624,900   
4             3.28  Albania1987         NaN   2,156,624,900   

   GdpPerCapitalMoney       Generation  
0                 796     Generation X  
1                 796           Silent  
2                 796     Generation X  
3                 796  G.I. Generation  
4                 796          Boomers

In [0]:
#We saw earlier that HDIForYear column had lots of isnull values, so lets explore that
m_data.isnull().sum()

Country                   0
Year                      0
Gender                    0
Age                       0
SuicidesNo                0
Population                0
Suicides100kPop           0
CountryYear               0
HDIForYear            19456
GdpForYearMoney           0
GdpPerCapitalMoney        0
Generation                0
dtype: int64

In [0]:
#The countryyear column is simply a concat of columns 1 and 2, and the HDIforyear seems unsualbe due to the large number of NaNs, so lets drop them
m_data.drop(['CountryYear', 'HDIForYear'], axis=1)

In [0]:
#Find out what is the min and max value for Year

#select and plot data by country, by gender for the most recent  year, 
len(m_data[(m_data['Year']==1985)].Country.unique())

48

In [0]:
years = m_data['Year'].unique()
years

array([1987, 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
       2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       1985, 1986, 1990, 1991, 2012, 2013, 2014, 2015, 2011, 2016])

In [0]:
unique_year_count = []
for year in years:
  unique_year_count.append(len(m_data[m_data['Year']==year]['Country'].unique()))
print(unique_year_count)

[54, 49, 52, 65, 65, 68, 78, 77, 77, 79, 83, 86, 88, 86, 86, 84, 84, 85, 86, 85, 89, 88, 48, 48, 64, 64, 81, 80, 78, 62, 86, 16]


In [0]:
len(m_data[m_data['Year']==year]['Country'].unique())

In [0]:
year

In [0]:
#chart it out 
plt.figure(figsize=(10, 10))
sns.barplot( x=years, y=unique_year_count)
plt.show()

In [0]:
#ratio of men vs. women who committed suicide in the countries we have data about in 1985 

#first how many countries we have data of
countries = m_data['Country'].unique()
countries
years = m_data['Year'].unique()
years

array([1987, 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
       2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       1985, 1986, 1990, 1991, 2012, 2013, 2014, 2015, 2011, 2016])

In [0]:
countries

In [0]:
#select the suicide rate corresponding to each country
m_data_for_this_year = m_data[m_data['Year']==1985]
  

In [0]:
m_countries = m_data_for_this_year['Country'].unique()

In [3]:
# load an example dataset
from vega_datasets import data
cars = data.cars()

# plot the dataset, referencing dataframe column names
import altair as alt
alt.Chart(cars).mark_bar().encode(
  x=alt.X('Miles_per_Gallon', bin=True),
  y='count()',
)

Chart({
  data:      Acceleration  Cylinders  Displacement  Horsepower  Miles_per_Gallon  \
  0            12.0          8         307.0       130.0              18.0   
  1            11.5          8         350.0       165.0              15.0   
  2            11.0          8         318.0       150.0              18.0   
  3            12.0          8         304.0       150.0              16.0   
  4            10.5          8         302.0       140.0              17.0   
  5            10.0          8         429.0       198.0              15.0   
  6             9.0          8         454.0       220.0              14.0   
  7             8.5          8         440.0       215.0              14.0   
  8            10.0          8         455.0       225.0              14.0   
  9             8.5          8         390.0       190.0              15.0   
  10           17.5          4         133.0       115.0               NaN   
  11           11.5          8         350.0       165.0               NaN   
  12           11.0          8         351.0       153.0               NaN   
  13           10.5          8         383.0       175.0               NaN   
  14           11.0          8         360.0       175.0               NaN   
  15           10.0          8         383.0       170.0              15.0   
  16            8.0          8         340.0       160.0              14.0   
  17            8.0          8         302.0       140.0               NaN   
  18            9.5          8         400.0       150.0              15.0   
  19           10.0          8         455.0       225.0              14.0   
  20           15.0          4         113.0        95.0              24.0   
  21           15.5          6         198.0        95.0              22.0   
  22           15.5          6         199.0        97.0              18.0   
  23           16.0          6         200.0        85.0              21.0   
  24           14.5          4          97.0        88.0              27.0   
  25           20.5          4          97.0        46.0              26.0   
  26           17.5          4         110.0        87.0              25.0   
  27           14.5          4         107.0        90.0              24.0   
  28           17.5          4         104.0        95.0              25.0   
  29           12.5          4         121.0       113.0              26.0   
  ..            ...        ...           ...         ...               ...   
  376          18.6          4         112.0        88.0              27.0   
  377          18.0          4         112.0        88.0              34.0   
  378          16.2          4         112.0        85.0              31.0   
  379          16.0          4         135.0        84.0              29.0   
  380          18.0          4         151.0        90.0              27.0   
  381          16.4          4         140.0        92.0              24.0   
  382          20.5          4         151.0         NaN              23.0   
  383          15.3          4         105.0        74.0              36.0   
  384          18.2          4          91.0        68.0              37.0   
  385          17.6          4          91.0        68.0              31.0   
  386          14.7          4         105.0        63.0              38.0   
  387          17.3          4          98.0        70.0              36.0   
  388          14.5          4         120.0        88.0              36.0   
  389          14.5          4         107.0        75.0              36.0   
  390          16.9          4         108.0        70.0              34.0   
  391          15.0          4          91.0        67.0              38.0   
  392          15.7          4          91.0        67.0              32.0   
  393          16.2          4          91.0        67.0              38.0   
  394          16.4          6         181.0       110.0              25.0   
  395   

In [0]:
male_suicide_rate_by_country = []
female_suicide_rate_by_country = []
for country in m_countries:
  male_suicide_rate_by_country.append()

In [0]:
from vega_datasets import data
stocks = data.stocks()

import altair as alt
alt.Chart(stocks).mark_line().encode(
  x='date:T',
  y='price',
  color='symbol'
).interactive(bind_y=False)

In [8]:
from vega_datasets import data
stocks = data.stocks()

import altair as alt
alt.Chart(stocks).mark_line().encode(
  x='date:T',
  y='price',
  color='symbol'
).interactive(bind_y=False)

Chart({
  data:     symbol       date   price
  0     MSFT 2000-01-01   39.81
  1     MSFT 2000-02-01   36.35
  2     MSFT 2000-03-01   43.22
  3     MSFT 2000-04-01   28.37
  4     MSFT 2000-05-01   25.45
  5     MSFT 2000-06-01   32.54
  6     MSFT 2000-07-01   28.40
  7     MSFT 2000-08-01   28.40
  8     MSFT 2000-09-01   24.53
  9     MSFT 2000-10-01   28.02
  10    MSFT 2000-11-01   23.34
  11    MSFT 2000-12-01   17.65
  12    MSFT 2001-01-01   24.84
  13    MSFT 2001-02-01   24.00
  14    MSFT 2001-03-01   22.25
  15    MSFT 2001-04-01   27.56
  16    MSFT 2001-05-01   28.14
  17    MSFT 2001-06-01   29.70
  18    MSFT 2001-07-01   26.93
  19    MSFT 2001-08-01   23.21
  20    MSFT 2001-09-01   20.82
  21    MSFT 2001-10-01   23.65
  22    MSFT 2001-11-01   26.12
  23    MSFT 2001-12-01   26.95
  24    MSFT 2002-01-01   25.92
  25    MSFT 2002-02-01   23.73
  26    MSFT 2002-03-01   24.53
  27    MSFT 2002-04-01   21.26
  28    MSFT 2002-05-01   20.71
  29    MSFT 2002-06-01   22.25
  ..     ...        ...     ...
  530   AAPL 2007-10-01  189.95
  531   AAPL 2007-11-01  182.22
  532   AAPL 2007-12-01  198.08
  533   AAPL 2008-01-01  135.36
  534   AAPL 2008-02-01  125.02
  535   AAPL 2008-03-01  143.50
  536   AAPL 2008-04-01  173.95
  537   AAPL 2008-05-01  188.75
  538   AAPL 2008-06-01  167.44
  539   AAPL 2008-07-01  158.95
  540   AAPL 2008-08-01  169.53
  541   AAPL 2008-09-01  113.66
  542   AAPL 2008-10-01  107.59
  543   AAPL 2008-11-01   92.67
  544   AAPL 2008-12-01   85.35
  545   AAPL 2009-01-01   90.13
  546   AAPL 2009-02-01   89.31
  547   AAPL 2009-03-01  105.12
  548   AAPL 2009-04-01  125.83
  549   AAPL 2009-05-01  135.81
  550   AAPL 2009-06-01  142.43
  551   AAPL 2009-07-01  163.39
  552   AAPL 2009-08-01  168.21
  553   AAPL 2009-09-01  185.35
  554   AAPL 2009-10-01  188.50
  555   AAPL 2009-11-01  199.91
  556   AAPL 2009-12-01  210.73
  557   AAPL 2010-01-01  192.06
  558   AAPL 2010-02-01  204.62
  559   AAPL 2010-03-01  223.02
  
  [560 rows x 3 columns],
  encoding: FacetedEncoding({
    color: Color({
      shorthand: 'symbol'
    }),
    x: X({
      shorthand: 'date:T'
    }),
    y: Y({
      shorthand: 'price'
    })
  }),
  mark: 'line',
  selection: {'selector006': SelectionDef({
    bind: 'scales',
    encodings: ['x'],
    type: 'interval'
  })}
})

In [0]:
m_data_year_country = m_data_for_this_year[m_data_for_this_year['Country']== 'Mexico']

In [0]:
m_data_year_country_gender = m_data_year_country[m_data_year_country['Gender']=='male']

In [0]:
np.sum(m_data_year_country_gender['SuicidesNo'])

1279

In [0]:
m_data_year_country_gender = m_data_year_country[m_data_year_country['Gender']=='female']

In [0]:
np.sum(m_data_year_country_gender['SuicidesNo'])

265

In [0]:
#putting it all together 
years = m_data['Year'].unique()
years

array([1987, 1988, 1989, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
       2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       1985, 1986, 1990, 1991, 2012, 2013, 2014, 2015, 2011, 2016])

In [0]:
years.sort()

In [0]:
years

array([1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
       1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

In [0]:
years = years[-8:]

In [0]:
years

array([2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

In [0]:
results_dict = {}
for year in years:
  results_dict[year] = {}
  #unique countreis for this year
  df_year = m_data[m_data['Year']==year]
  countries = np.sort(df_year['Country'].unique())
  
  for country in countries:
    results_dict[year][country] = []
    df_year_country = df_year[df_year['Country'] == country]
    #append female at position 1
    df_year_country_fm  = df_year_country[df_year_country['Gender']=='female']
    df_year_country_m = df_year_country[df_year_country['Gender']=='male']
    results_dict[year][country].append(np.sum(df_year_country_fm['SuicidesNo']))
    results_dict[year][country].append(np.sum(df_year_country_m['SuicidesNo']))
    
  
  

In [0]:
results_dict

In [0]:
#plot for 2009 
plot_data = results_dict[2016]
plot_data

In [0]:
ys = list(plot_data.values())